### ISSUE TITLE
Chinese input break the cursor

### ISSUE THREAD

**Issue by linonetwo** [zhw2590582/term-web#1]
Try input "sss搜索" and press ← and try delete some word

**Comment by zhw2590582** [comment]
I have disabled the arrow keys while typing. I have tried many times and cannot reproduce your steps. What browser do you have and what is the version number?

**Comment by linonetwo** [comment]
Oh, seems it not caused by chinese.

try input 123456, and type ← and delete, you will find 5 be deleted.

I'm in Firefox 75 and MacOS

**Comment by zhw2590582** [comment]
Thanks for the feedback, the problem has been found and has been fixed
