### ISSUE TITLE
大佬找工作是否考虑字节跳动？

### ISSUE THREAD

**Issue by huruji** [zhw2590582/term-web#2]
暂时没找到大佬的 blog，就冒昧在这里问一句了

**Comment by zhw2590582** [comment]
哈哈，之前你们公司都有好几个人找过我投简历了，但我投了一次之后就说我不合适，估计学历不太行。

**Comment by huruji** [comment]
> 哈哈，之前你们公司都有好几个人找过我投简历了，但我投了一次之后就说我不合适，估计学历不太行。

发我看看嘞，我们部门正在大量找人呢～
