### ISSUE TITLE
[Bug|UI]: Newline before input

### ISSUE THREAD

**Issue by Chaostheorie** [zhw2590582/term-web#4]
Thank you for your wonderful work on this library. I'm currently trying to integrate it as an interactive shell for a REPL, but I'm stuck with an additional seemingly bugged newline after every entered command. This error is reproducible in the online demo ([recording](https://litter.catbox.moe/ne1dvj.webm)). I also couldn't find any obvious indication why it happened using debug mode.

## System

- OS: MX 19 / Linux 5.8.0-3 / Mozilla Firefox 90.0.2
- Package: term-web@1.1.9

## Steps to reproduce

> See [video](https://litter.catbox.moe/ne1dvj.webm)

1. Enter a command and press enter
2. type something

**Comment by zhw2590582** [comment]
Fixed in `1.1.11`

**Comment by Chaostheorie** [comment]
Thank you for the fix :)
