### ISSUE TITLE
[Pages] term-web.js.org returns 404

### ISSUE THREAD

**Issue by Chaostheorie** [zhw2590582/term-web#5]
## Problem

Accessing [term-web.js.org](https://term-web.js.org/), as referenced in the repository, results in a 404 (not found) error on GH Pages. Has a deployment pipeline or something similar failed?

**Comment by zhw2590582** [comment]
Yes, it was resolved after re-running CI

**Comment by Chaostheorie** [comment]
Thank you. The new update looks awesome
